---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    jirauri: "https://globomantics.atlassian.net"
  tasks:
    - name: Create a Jira Issue
      community.general.jira:
        uri: '{{jirauri}}'
        username: '{{username}}'
        password: '{{password}}'
        project: IP
        operation: edit
        issue: IP-3
        account_id: 61270c330952180069eff12b
        issuetype: Task
