---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    jirauri: "https://globomantics.atlassian.net"
  tasks:
    - name: Create a Jira Issue
      community.general.jira:
        uri: '{{jirauri}}'
        username: '{{username}}'
        password: '{{password}}'
        project: IP
        operation: comment
        comment: This is my first comment
        issue: IP-7
