---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    jirauri: "https://globomantics.atlassian.net"
  tasks:
    - name: Create a Jira Issue
      community.general.jira:
        uri: '{{jirauri}}'
        username: '{{username}}'
        password: '{{password}}'
        project: IP
        operation: create
        issuetype: Task
        summary: Integration Issue
        description: Third issue to be created from ansible
